name: affe
type: contrastive
cuda_devices: [0, 1, 2, 3]
random_seed: 0

supervised: true
label: valence-arousal

model:
  model_ckpt: google/vit-base-patch16-224-in21k
  z_dims: 64

train:
  num_epochs: 10
  batch_size: 512
  learning_rate: 0.0001
  weight_decay: 0.0001
  warmup_steps: 0
  logging_strategy: steps
  logging_steps: 50

data:
  images_root: ../Affectnet/Manually_Annotated/Manually_Annotated_Images/
  train_csv: ../Affectnet/training.csv
  val_csv: ../Affectnet/validation.csv
  train_invalid_files:
    [103/29a31ebf1567693f4644c8ba3476ca9a72ee07fe67a5860d98707a0a.jpg]
  val_invalid_files: []
  exclude_labels:
    - 8
    - 9
    - 10

wandb:
  project: Affectnet-vit
  group: head-align
