name: CL_catval_z256_bs512
type: contrastive
cuda_devices: [0, 1, 2, 3]
random_seed: 0

supervised: true
label: categorical-valence

model:
  model_ckpt: google/vit-base-patch16-224-in21k
  z_dims: 256

train:
  num_epochs: 8
  batch_size: 512
  learning_rate: 0.0002
  weight_decay: 0.001
  logging_strategy: steps
  logging_steps: 100

data:
  images_root: ../Affectnet/Manually_Annotated/Manually_Annotated_Images/
  train_csv: ../Affectnet/training.csv
  val_csv: ../Affectnet/validation.csv
  train_invalid_files:
    [103/29a31ebf1567693f4644c8ba3476ca9a72ee07fe67a5860d98707a0a.jpg]
  val_invalid_files: []
  exclude_labels:
    - 8
    - 9
    - 10

wandb:
  project: Affectnet-vit
  group: A100-CL
