hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: ./

defaults:
  - exp: contrastive/contrastive-default
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
