name: contrastive
type: contrastive
cuda_devices: [0, 1, 2, 3]

supervised: true
label: expression

model:
  model_ckpt: google/vit-base-patch16-224-in21k
  z_dims: 128

train:
  num_epochs: 10
  batch_size: 16
  learning_rate: 0.00001
  weight_decay: 0.0001
  logging_strategy: steps
  logging_steps: 1000

data:
  images_root: ../Affectnet/
  train_csv: ../Affectnet/training.csv
  val_csv: ../Affectnet/validation.csv
  train_invalid_files:
    [103/29a31ebf1567693f4644c8ba3476ca9a72ee07fe67a5860d98707a0a.jpg]
  val_invalid_files: []
  exclude_labels:
    - 8
    - 9
    - 10

wandb:
  project: test-contrastive
  group: test
